services:
  #  HADOOP (4 services) 
  namenode:
    build: .
    image: velolyon/hadoop:3.4.3
    container_name: namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "9000:9000"
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
    volumes:
      - ./:/opt/project
    networks: [velolyon]

  datanode:
    build: .
    image: velolyon/hadoop:3.4.3
    container_name: datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    ports:
      - "9864:9864"
    env_file:
      - ./config
    depends_on: [namenode]
    networks: [velolyon]

  resourcemanager:
    build: .
    image: velolyon/hadoop:3.4.3
    container_name: resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    env_file:
      - ./config
    depends_on: [namenode]
    volumes:
      - ./:/opt/project
    networks: [velolyon]

  nodemanager:
    build: .
    image: velolyon/hadoop:3.4.3
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    depends_on: [resourcemanager]
    networks: [velolyon]

  #  HIVE 
  hive:
    image: apache/hive:4.0.0
    container_name: hive
    depends_on: [namenode, datanode]
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Xmx1G -Dfs.defaultFS=hdfs://namenode:9000"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./:/opt/project
    networks: [velolyon]

  #  KAFKA 
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [velolyon]

  #  ATLAS 
  atlas:
    image: sburn/apache-atlas:2.3.0
    container_name: atlas
    ports:
      - "21000:21000"
    command: >
      /bin/bash -c "/opt/apache-atlas-2.3.0/bin/atlas_start.py && tail -f /dev/null"
    networks: [velolyon]

networks:
  velolyon:
    driver: bridge
